# Generated by Django 3.1.5 on 2021-01-26 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profileimage', models.ImageField(blank=True, default='defaultimage/svg.png', null=True, upload_to='userimage')),
                ('GENDER', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=5)),
                ('FirstName', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('LastName', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('City', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('Country', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('Aboutme', models.TextField(blank=True, default=' ', max_length=50, null=True)),
                ('user', models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('Images', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('like', models.ManyToManyField(blank=True, related_name='post_like', to=settings.AUTH_USER_MODEL)),
                ('save', models.ManyToManyField(blank=True, related_name='post_save', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ManyToManyField(blank=True, related_name='Followingdata', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ManyToManyField(blank=True, related_name='follower', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
