# Generated by Django 3.1.5 on 2021-01-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pixabayuser', '0003_auto_20210126_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
