# Generated by Django 3.1.5 on 2021-01-26 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pixabayuser', '0022_auto_20210126_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='save',
            field=models.ManyToManyField(related_name='post_save', to=settings.AUTH_USER_MODEL),
        ),
    ]
