# Generated by Django 3.1.5 on 2021-01-26 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pixabayuser', '0023_auto_20210126_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='save',
            field=models.ManyToManyField(blank=True, related_name='post_save', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='auth.user'),
            preserve_default=False,
        ),
    ]
