# Generated by Django 3.1.5 on 2021-01-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pixabayuser', '0024_auto_20210126_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepost',
            old_name='save',
            new_name='save_post',
        ),
    ]
