# Generated by Django 3.1.5 on 2021-01-27 07:11

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('Pixabayuser', '0026_auto_20210126_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
