# Generated by Django 3.1.5 on 2021-01-28 06:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Pixabayuser', '0027_imagepost_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, editable=False, unique=True),
        ),
    ]
