# Generated by Django 3.1.5 on 2021-01-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pixabayuser', '0030_auto_20210128_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
