# Generated by Django 3.1.5 on 2021-01-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pixabayuser', '0031_auto_20210128_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='videofile',
            field=models.FileField(null=True, upload_to='deploy/videos/%Y/%m/%d/', verbose_name=''),
        ),
    ]
