# Generated by Django 3.1.5 on 2021-01-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pixabayuser', '0032_imagepost_videofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='videofile',
        ),
    ]
